services:
  backend:
    image: ${REGISTRY}/${NAMESPACE}/${BACKEND_IMAGE}:${IMAGE_TAG}
    restart: unless-stopped
    networks:
      - outdoor-network

  frontend:
    image: ${REGISTRY}/${NAMESPACE}/${FRONTEND_IMAGE}:${IMAGE_TAG}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - outdoor-network

networks:
  outdoor-network:
    driver: bridge
