services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    container_name: szhuwai-backend
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - http_proxy=
      - https_proxy=
      - PROXY_HTTP=
      - PROXY_HTTPS=
    volumes:
      - ./backend/temp_tracks:/app/temp_tracks

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    container_name: szhuwai-frontend
