[mypy]
python_version = 3.10
strict = True
explicit_package_bases = True
namespace_packages = True

[mypy-alibabacloud_dysmsapi20170525.*]
ignore_missing_imports = True
[mypy-alibabacloud_tea_openapi.*]
ignore_missing_imports = True
[mypy-alibabacloud_tea_util.*]
ignore_missing_imports = True
